export const ACTIONS = {
  ADD_POSTS: 'ADD_POSTS',
  GET_POST: 'GET_POST',
  CLEAN_POST_STATE: 'CLEAN_POST_STATE',
  SEARCH_GIFS: 'SEARCH_GIFS',
  FETCH_POSTS: 'FETCH_POSTS',
  SAVE_POST: 'SAVE_POST',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  SIGN_OUT: 'SIGN_OUT',
};
